sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ATotade/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ATotade/docker-react npm run test -- --coverage
